name: CI/CD for React App

on:
  push:
    branches:
      - main # Trigger workflow on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Use Node.js 20 for the build step

      # Step 3: Install dependencies and build the React app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
          # Debugging: Check if the build/ folder exists
          echo "Listing build folder:"
          ls -al build
      # Step 4: Deploy to VPS
      - name: Transfer build files to VPS
        run: |
          echo "Creating temporary SSH key file..."
          echo "${{ secrets.VPS_KEY }}" > ssh_key  # Write the private key to a temporary file
          chmod 600 ssh_key  # Set the correct permissions for the SSH key file
          echo "Transferring build files to VPS..."
          scp -r -o StrictHostKeyChecking=no -i ssh_key build/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/my-react-app/
          echo "Files transferred successfully!"
          echo "Cleaning up temporary SSH key..."
          rm -f ssh_key  # Remove the temporary SSH key file
      # Step 5: Verify deployment
      - name: Verify deployment on VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            echo "Checking deployed files on VPS..."
            ls -al /var/www/my-react-app/
